on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: test-coverage

permissions: read-all

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      CRAN: https://packagemanager.posit.co/cran/__linux__/noble/latest
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      ART_RUN_AS_DEMO: FALSE
      ART_USE_PG_CONF: ${{ secrets.ART_USE_PG_CONF }}
      ART_PG_USER_PASSWD_PRD: ${{ secrets.ART_PG_USER_PASSWD_PRD }}
      ART_BUCKETS_KEY_ID: ${{ secrets.ART_BUCKETS_KEY_ID }}
      ART_BUCKETS_KEY_SECRET: ${{ secrets.ART_BUCKETS_KEY_SECRET }}
      ART_OPENAI_KEY: ${{ secrets.ART_OPENAI_KEY }}
      ART_OPENSEA_KEY: ${{ secrets.ART_OPENSEA_KEY }}


    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup R (Latest)
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          print(cov)
          covr::to_cobertura(cov)
        shell: Rscript {0}

      - name: Send Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          # Fail if error if not on PR, or if on PR and token is given
          fail_ci_if_error: ${{ github.event_name != 'pull_request' || secrets.CODECOV_TOKEN }}
          files: ./cobertura.xml
          plugins: noop
          disable_search: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package

